// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkjysqkxfbrnguvqspfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJranlzcWt4ZmJybmd1dnFzcGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjU5MjEsImV4cCI6MjA2MTAwMTkyMX0.fvTnP6Zh89mSjBYgqWqdlOxBRqlDle510rN3JjqRG0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);